DROP TABLE IF EXISTS Tracks;

CREATE TABLE IF NOT EXISTS Tracks (
  ID VARCHAR(20) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  ARTIST VARCHAR(50) NOT NULL,
  LENGTH INT NULL,
  BPM INT NULL,
  PRIMARY KEY (ID)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
